export default [
    {
        id: 1,
        name: "Weyland",
        description: "Weyland-Yutani stuff",
        value: 100000,
    },
    {
        id: 2,
        name: "Krusty Krab",
        description: "Krusty Krub stuff",
        value: 20000,
    },
    {
        id: 3,
        name: "Monster",
        description: "Monster drink",
        value: 30000,
    },
    {
        id: 4,
        name: "Majoriarato",
        description: "Games and goods from Majoriarato",
        value: 50000,
    },
    {
        id: 5,
        name: "Coke",
        description: "Coke supplies",
        value: 30000,
    },
    {
        id: 6,
        name: "7up",
        description: "7up soda drink",
        value: 40000,
    },
    {
        id: 7,
        name: "YouTube",
        description: "Youtube kitten videos",
        value: 30000,
    },
    {
        id: 8,
        name: "Plenny Shake",
        description: "Affordable meal shake",
        value: 5000000,
    },
    {
        id: 9,
        name: "KAS",
        description: "Refreshing beverages",
        value: 50000,
    },
    {
        id: 10,
        name: "Love",
        description: "Alva & Guinxu's secrets",
        value: 6969,
    },
    {
        id: 11,
        name: "Ice Cream",
        description: "Absolute-zero ice cream",
        value: 20000,
    },
    {
        id: 12,
        name: "Pokentainer",
        description: "Gotta catch'em all",
        value: 20000,
    },
    {
        id: 13,
        name: "Nido",
        description: "Food for birds",
        value: 54000,
    },
    {
        id: 14,
        name: "JavaScript",
        description: "JavaScript frameworks",
        value: 880000,
    },
];