export default [
    "San Angelo",
    "San Antonio",
    "San Antonio",
    "Saint Augustine",
    "Saint Augustine Beach",
    "San Benito",
    "San Bernardino",
    "San Bruno",
    "San Buenaventura",
    "San Carlos",
    "San Clemente",
    "San Diego",
    "San Diego",
    "San Dimas",
    "San Elizario",
    "San Fernando",
    "San Francisco",
    "San Gabriel",
    "San Jacinto",
    "San Joaquin",
    "San Jose",
    "San Juan",
    "San Juan Bautista",
    "San Juan Capistrano",
    "San Leandro",
    "San Luis",
    "San Luis Obispo",
    "San Marcos",
    "San Marcos",
    "San Mateo",
    "San Pablo",
    "San Perlita",
    "San Rafael",
    "San Ramon",
    "San Saba",
    "Santa Ana",
    "Santa Barbara",
    "Santa Clara",
    "Santa Clara",
    "Santa Clara",
    "Santa Clarita",
    "Santa Cruz",
    "Santa Fe",
    "Santa Fe",
    "Santa Fe Springs",
    "San Marcos",
    "Santa Anna",
    "Santa Maria",
    "Santa Monica",
    "Santaquin",
    "Santa Rita Park",
    "Santa Rosa",
    "Santa Rosa",
    "La Cañada Flintridge",
    "La Grulla",
    "Laguna Beach",
    "La Habra",
    "La Joya",
    "La Junta",
    "Lake Buena Vista",
    "La Mesa",
    "La Mirada",
    "La Plata",
    "La Plata",
    "La Puente",
    "La Quinta",
    "La Palma",
    "La Verkin",
    "La Villa",
    "Laredo",
    "La Vista",
    "Las Cruces",
    "Las Vegas",
    "Las Vegas",
    "Leon",
    "Lima",
    "Little Havana",
    "Los Alamitos",
    "Los Alamos",
    "Los Angeles",
    "Los Banos",
    "Los Fresnos",
    "Los Gatos",
    "Los Ybanez",
    "Agua Caliente",
    "Agua Linda",
    "Agua Nueva",
    "Aguila",
    "Alamo",
    "Alcalde",
    "Alhambra Valley",
    "Almeria",
    "Algodones",
    "Alta",
    "Altamont",
    "Alto",
    "Alto Bonito Heights",
    "Alto",
    "Alto Bonito",
    "Amada Acres",
    "Amado",
    "Amigo",
    "Anacua",
    "Anza",
    "Arboles",
    "Arroyo Del Agua",
    "Arroyo Gardens",
    "Asuncion",
    "Bahia",
    "Ballena",
    "Barco",
    "Barrera",
    "Bayo Vista",
    "Benjamin Perez",
    "Boca Del Mar",
    "Boca Pointe",
    "Boca Raton",
    "Bonanza",
    "Bonita",
    "Bonita",
    "Bonita",
    "Bonita",
    "Brazos",
    "Brazos",
    "Brito",
    "Buena Vista",
    "Caballo",
    "Cadiz",
    "Cadiz",
    "Caliente",
    "Callao",
    "Camino",
    "Camino Tassajara",
    "Campo",
    "Campo Verde",
    "Canjilon",
    "Cañoncito",
    "Canova",
    "Canyon",
    "Capitan",
    "Carlos",
    "Carmen",
    "Carthagena",
    "Casa Blanca",
    "Casa Piedra",
    "Casas",
    "Casas Adobes",
    "Castro Valley",
    "Cazadero",
    "Cebolla",
    "Cedro",
    "Cesar Chavez",
    "Chalco",
    "Chamita",
    "Chaparrito",
    "Chimayo",
    "Cimarron",
    "Cimarron Hills",
    "Cimarron",
    "Colonia",
    "Colyell",
    "Concepcion",
    "Conejo",
    "Conejos",
    "Contra Costa",
    "Cordova",
    "Corona",
    "Coronado",
    "Corte Madera",
    "Cortez",
    "Coto de Caza",
    "Coyote",
    "Cuba",
    "Cuchara",
    "Cuzco",
    "Del Rey",
    "De Soto",
    "Descanso",
    "Dulzura",
    "Dinero",
    "Dos Cabezas",
    "Dos Palos Y",
    "Dulce",
    "East Alto Bonito",
    "East Lopez",
    "East Verde Estates",
    "El Capitán",
    "El Castillo",
    "El Chaparral",
    "El Dorado",
    "El Duende",
    "El Nido",
    "El Rancho",
    "El Rancho Vela",
    "El Refugio",
    "El Rito",
    "El Sobrante",
    "El Socio",
    "Elias-Fela Solis",
    "Embudo",
    "Ensenada",
    "Escobar I",
    "Espanola",
    "Espanola",
    "Eugenio Saenz",
    "Falcon Heights",
    "Falcon Village",
    "Falconaire",
    "Fernando Salinas",
    "Agua Caliente",
    "Flor del Rio",
    "Fronton",
    "Galisteo",
    "Gallina",
    "Galvez",
    "Ganado",
    "Garcia",
    "Garciasville",
    "Gardnerville Ranchos",
    "Garza-Salinas II",
    "Gaviota",
    "Golondrinas",
    "Gomez",
    "Gonzalez",
    "Guadalupe-Guerra",
    "Guerra",
    "Campo Verde",
    "Halchita",
    "Havana",
    "Havana",
    "Havana",
    "Havana",
    "Havana",
    "Hernando",
    "Hernandez",
    "Huerfano",
    "Indio",
    "Isla Vista",
    "Isleta Village Proper",
    "Jacinto",
    "Jardin de San Julian",
    "JF Villarreal",
    "Juntura",
    "La Blanca",
    "La Carla",
    "La Casita-Garciasville",
    "La Cienega",
    "La Chuparosa",
    "La Escondida",
    "La Esperanza",
    "Las Flores",
    "La Gloria",
    "La Homa",
    "La Madera",
    "La Mesilla",
    "La Puerta",
    "La Reforma",
    "La Rosita",
    "La Victoria",
    "La Loma de Falcon",
    "La Sal",
    "La Villita",
    "Las Lomas",
    "Las Lomitas",
    "Las Palmas-Juarez",
    "Las Tablas",
    "Las Trampas",
    "Laguna",
    "Laguna Beach",
    "Lagunitas",
    "Lagunitas-Forest Knolls",
    "Laguna Seca",
    "Lajitas",
    "La Minita",
    "La Paloma Ranchettes",
    "Lago Vista",
    "La Minita",
    "Lima",
    "Linda",
    "Llano Grande",
    "Loma Linda East",
    "Loma Vista",
    "Longoria",
    "Los Alvarez",
    "Los Arrieros",
    "Los Barreras",
    "Los Berros",
    "Los Ebanos",
    "Los Luceros",
    "Los Ojos",
    "Los Osos",
    "Los Ranchos",
    "Los Villareales",
    "Lopezville",
    "Los Ebanos",
    "Loxa",
    "Madera Canyon",
    "Madrid",
    "Madrid",
    "Madrid",
    "Malaga",
    "Manuel Garcia",
    "Manuel Garcia II",
    "Manzano",
    "Manzano Springs",
    "Marina del Rey",
    "Mariposa",
    "Marrero",
    "Martinez",
    "Martinez",
    "Martinez",
    "Matagorda",
    "Matamoras",
    "Medanales",
    "Mendocino",
    "Mesa",
    "Mesa",
    "Mesa del Caballo",
    "Mesa Vista",
    "Mexican Hat",
    "Mexico",
    "Mi Ranchito Estate",
    "Mier",
    "Miranda",
    "Miranda",
    "Modena",
    "Montana",
    "Montana City",
    "Montana (community)",
    "Monte Alto",
    "Montecito",
    "Montezuma Creek",
    "La Mora",
    "Mosca",
    "Mount Vista",
    "Naranja",
    "Narciso Pena",
    "New Almaden",
    "New Santa Fe",
    "North Escobares",
    "North Lima",
    "North San Juan",
    "Nunez",
    "Oceano",
    "Ojo Caliente",
    "Ojo Sarco",
    "Ola",
    "Old Escobares",
    "Olivia Lopez de Gutierrez",
    "Oljato",
    "Oro Blanco",
    "Oso",
    "Pablo Pena",
    "Pacheco",
    "Pajaro",
    "Pajaro Dunes",
    "Pajarito Mesa",
    "Palo Blanco",
    "Palo Pinto",
    "Palomar Mountain",
    "Palominas",
    "Panama",
    "Pedro",
    "Pena",
    "Peña Blanca",
    "Peñasco",
    "Perote",
    "Petaca",
    "Pie",
    "Piedra",
    "Pilar",
    "Pintura",
    "Plumas Eureka",
    "Plumas Lake",
    "Ponderosa",
    "Ponderosa Pine",
    "Port Mahon",
    "Pozo",
    "Pueblito",
    "Pueblo of Sandia Village",
    "Quesada",
    "Quito",
    "Ramirez",
    "Ramirez-Perez",
    "Ramos",
    "Rancho Alegre",
    "Rancho Banquete",
    "Rancho Chico",
    "Rancho de la Parita",
    "Ranchos Penitas West",
    "Rancho San Diego",
    "Rancho Santa Fe",
    "Ranchos de Taos",
    "Ranchitos del Norte",
    "Rancho Viejo",
    "Raso",
    "Regino Ramirez",
    "Relampago",
    "Rio Chiquito",
    "Rio Creek",
    "Rio Grande",
    "Rio Rico",
    "Rio Verde",
    "Rios",
    "Rivera",
    "Rodeo",
    "Rodeo",
    "Salida",
    "Salineño",
    "Salineño North",
    "Saltillo",
    "Saltillo",
    "Saltillo",
    "Sammy Martinez",
    "San Antonito",
    "San Carlos",
    "San Carlos",
    "San Carlos Park",
    "San Cristobal",
    "San Fernando",
    "San Gregorio",
    "San Isidro",
    "San Jose",
    "San Jose",
    "San Juan",
    "San Juan",
    "San Lorenzo",
    "San Lorenzo",
    "San Lucas",
    "San Martin",
    "San Miguel",
    "San Miguel",
    "San Pablo",
    "San Pedro",
    "San Ramon",
    "San Simeon",
    "San Simon",
    "Sandia",
    "Sandia Park",
    "Sandia",
    "Sandoval",
    "Sangre de Cristo",
    "Santa Ana Pueblo",
    "Santa Anna",
    "Santa Catarina",
    "Santa Cruz",
    "Santa Cruz",
    "Santa Cruz",
    "Santa Elena",
    "Santa Rita Park",
    "Santa Rosa",
    "Santa Fe",
    "Santa Fe",
    "Santa Fe",
    "Santa Fe",
    "Santa Fe",
    "Santa Maria",
    "Santa Margarita",
    "Santa Monica",
    "Santa Nella",
    "Santa Susana",
    "Santa Rosa",
    "Santa Ysabel",
    "Santo",
    "Saragossa",
    "Sarita",
    "Sebastian",
    "Sebastian",
    "Seville",
    "Sierra Blanca",
    "San Simeon",
    "Seboyeta",
    "Sobrante",
    "Spanish Valley",
    "Sunol",
    "Tassajara",
    "Terlingua",
    "Tierra Amarilla",
    "Tierra Del Mar",
    "Tierra Dorada",
    "Tome-Adelino",
    "Toro Canyon",
    "Trinidad",
    "Truchas",
    "Uva",
    "Uvalde Estates",
    "Valdez",
    "Valencia West",
    "Valencia",
    "Valle Hermoso",
    "Valle Vista",
    "Valle Vista",
    "Vallecitos",
    "Val Verde",
    "Val Verde Park",
    "Velarde",
    "Vera Cruz",
    "Veyo",
    "Victor",
    "Victoria Vera",
    "Vida",
    "Vida",
    "Vida",
    "Villarreal",
    "Vista Center",
    "Vista West",
    "Villanueva",
    "Villas",
    "Vista Santa Rosa",
    "Washington-on-the-Brazos",
    "West Alto Bonito",
    "West Lima",
    "White Mesa",
    "Yucatan Landing",
    "Yucatan",
    "Yucatan",
    "Zamora",
    "Districts and boroughs",
    "Armada Road Multi-Family District",
    "Bogota",
    "Corona del Mar",
    "Matamoras",
    "Villa Rica",
    "Saltillo",
    "San Ysidro",
    "Valencia"
];