export default {
    text1: {title: "This is a text", size: 40, items: [{ text: "point1"}, { text: "point2"},{ text: "point3"}] },
    text2: {title: "This is a 2nd text", size: 40, items: [] },
    text3: {title: "This is a 3rd text", size: 40, items: [] },
    text4: {title: "This is a 3rd text", size: 40, items: [] },
    text5: {title: "This is a 3rd text", size: 40, items: [] },
    text6: {title: "This is a 3rd text", size: 40, items: [] },
    text7: {title: "This is a 3rd text", size: 40, items: [] },
    text8: {title: "This is a 3rd text", size: 40, items: [] },
    text9: {title: "This is a 3rd text", size: 40, items: [] },
    text10: {title: "This is a 3rd text", size: 40, items: [] },
    text11: {title: "This is a 3rd text", size: 40, items: [] },
    text12: {title: "This is a 3rd text", size: 40, items: [] },
    text13: {title: "This is a 3rd text", size: 40, items: [] },
    text14: {title: "This is a 3rd text", size: 40, items: [] },
    text15: {title: "This is a 3rd text", size: 40, items: [] },
    text16: {title: "This is a 3rd text", size: 40, items: [] },
    text17: {title: "This is a 3rd text", size: 40, items: [] },
    text18: {title: "This is a 3rd text", size: 40, items: [] },
    text19: {title: "This is a 3rd text", size: 40, items: [] },
}
