export default ["The Twisting Pits",
"Quarters of the Renegade Witch",
"Lair of the Brutal Army",
"The Turbulent Lair",
"Caverns of the Infernal Orc",
"Maze of the Mourning Guardian",
"Caverns of the Lonely Oracle",
"Tunnels of the Furious Arachnid",
"Quarters of the Chaotic Warlord",
"The Dancing Caverns",
"The Forgotten Maze",
"Point of the Furious Marsh",
"The Spirit Tombs",
"Tombs of the Spirit Basilisk",
"The Mighty Grotto",
"The Withered Delves",
"Quarters of the Hidden Soldier",
"Point of the Furious Serpent",
"Haunt of the Conquered Ogre",
"The Abyss Cells",
"The Grim Quarters",
"The Burned Haunt",
"Dungeon of the Unspoken Knight",
"Haunt of the Silver Warrior",
"Grotto of the Unspoken Basilisk",
"Labyrinth of the Impostor Witch",
"Tunnels of the White Army",
"The Spirit Tombs",
"Tunnels of the Spirit Widow",
"Cells of the Hidden Priest",
"The Fire Labyrinth",
"The Yawning Burrows",
"The Western Burrows",
"The Desert Caverns",
"The Turbulent Lair",
"The Flowing Crypt",
"Haunt of the Conquered Ogre",
"Chambers of the Destroyed Phoenix",
"The Desert Caverns",
"The Turbulent Lair",
"Cells of the Dishonored Occult",
"Vault of the Conquered Legion",
"Cells of the Destroyed Phoenix",
"The Diamond Tunnels",
"Quarters of the White Forest",
"The Wraith Pits",
"Labyrinth of the Nightmare Serpent",
"The Bloodfall Haunt",
"The Howling Caverns",
"Burrows of the Forgotten Occult",
"The False Maze",
"Chambers of the Burning Paladin",
"Pits of the Ghost Hunter",
"The Living Dead Crypt",
"Haunt of the Vanished Horsemen",
"Pits of the Crying Forest",
"Cells of the Hidden Marsh",
"Caverns of the Infernal Scorpion",
"Catacombs of the Forsaken King",
"Dungeon of the Ebon Morass",
"Quarters of the Spirit Spider",
"The Adamantine Caverns",
"Dungeon of the Burning Ogre",
"Crypt of the Shadow Jungle",
"Grotto of the Doomed Goblin",
"The Bloodfall Maze",
"The Delusion Crypt",
"The Forgotten Burrows",
"Pits of the Silver Giant",
"Haunt of the Silver Warrior",
"Caverns of the Golden Knight",
"Cells of the Obsidian Warrior",
"Vault of the Ghost Mage",
"Vault of the Shadow Priest",
"Cells of the Doomed Serpent",
"Crypt of the Renegade Mage",
"Pits of the Ebon Panther",
"Point of the Enigmatic Scorpion",
"Tunnels of the Ancient Soldier",
"The Mystic Quarters",
"The Living Dead Catacombs",
"Maze of the Perished Phoenix",
"The Roaring Lair",
"Dungeon of the Vanishing Bat",
"Lair of the Burning Mage",
"Delves of the Enigmatic Elf",
"Labyrinth of the Scarlet Goblin",
"Vault of the Cursed Mountain",
"The Light Grotto",
"Lair of the Scarlet Oracle",
"Grotto of the Death's Priest",
"Cells of the Neglected Knight",
"Caverns of the Crying Panther",
"Quarters of the Mad Legion",
"Lair of the White Oracle",
"Crypt of the Savage Bear",
"The Yawning Burrows",
"Cells of the Mad Ogre",
"Grotto of the Golden Army",
"The Living Haunt",
"The Bottomless Vault",
"The Burned Labyrinth",
];