export default  {
  big_rat: { name: "Big Rat",description: "A large rat with sharp teeth.", attack: 3,defense: 1,value: 10,type: "enemy", health: 2},
    barbarian: { name: "Barbarian", description: "A barbarian.", attack: 10, defense: 5, value: 100, type: "enemy" , health: 10},
    chaos_warrior: { name: "Chaos Warrior", description: "A chaos warrior.", attack: 15, defense: 5, value: 100, type: "enemy" , health: 15},
    dwarf: { name: "Dwarf", description: "A dwarf.", attack: 12, defense: 5, value: 100, type: "enemy" , health: 15},
    evil_chest: { name: "Evil Chest", description: "An evil chest.", attack: 10, defense: 5, value: 100, type: "enemy" , health: 10},
    paladin: { name: "Paladin", description: "A paladin.", attack: 14, defense: 5, value: 100, type: "enemy" , health: 10},
    priest: { name: "Priest", description: "A priest.", attack: 10, defense: 5, value: 100, type: "enemy" , health: 10},
    ghost: { name: "Ghost", description: "A ghost.", attack: 10, defense: 5, value: 100, type: "enemy" , health: 5},
    princess: { name: "Princess", description: "A princess.", attack: 20, defense: 5, value: 100, type: "enemy" , health: 20},
    spider: { name: "Spider", description: "A spider.", attack: 11, defense: 5, value: 100, type: "enemy" , health: 5},
    warlock: { name: "Warlock", description: "A warlock.", attack: 11, defense: 5, value: 100, type: "enemy" , health: 10},
    bat: { name: "Bat", description: "A bat.", attack: 10, defense: 5, value: 100, type: "enemy" , health: 3},
    rat: { name: "Rat", description: "A rat.", attack: 10, defense: 5, value: 100, type: "enemy" , health: 1},
    wizard: { name: "Wizard", description: "A wizard.", attack: 10, defense: 5, value: 100, type: "enemy" , health: 10},
    knight: { name: "Knight", description: "A knight.", attack: 10, defense: 5, value: 100, type: "enemy" , health: 15},
    scorpion: { name: "Scorpion", description: "A scorpion.", attack: 10, defense: 5, value: 100, type: "enemy" , health: 5},
    wrath: { name: "Wrath", description: "A wrath.", attack: 10, defense: 5, value: 100, type: "enemy" , health: 10},
    battle_axe: { name: "Battle Axe", description: "A battle axe.", attack: 20, defense: 0, value: 100, type: "weapon" , health: 0},
    dagger: { name: "Dagger", description: "A small and agile dagger.", attack: 1, defense: 1, value: 10, type: "weapon" , health: 0},
    staff1: { name: "Staff", description: "A magical staff.", attack: 5, defense: 2, value: 35, type: "weapon" , health: 1},
    staff2: { name: "Staff", description: "A magical staff.", attack: 5, defense: 2, value: 100, type: "weapon" , health: 2},
    staff3: { name: "Staff", description: "A magical staff.", attack: 5, defense: 2, value: 30, type: "weapon" , health: 3},
    hammer: { name: "Hammer", description: "A hammer.", attack: 20, defense: 3, value: 60, type: "weapon" , health: 0},
    sword0: { name: "Sword", description: "A sword.", attack: 2, defense: 0, value: 30, type: "weapon" , health: 0},
    sword1: { name: "Sword", description: "A sword.", attack: 5, defense: 1, value: 50, type: "weapon" , health: 0},
    sword2: { name: "Sword", description: "A sword.", attack: 10, defense: 2, value: 70, type: "weapon" , health: 0},
    sword3: { name: "Sword", description: "A sword.", attack: 15, defense: 3, value: 80, type: "weapon" , health: 0},
    shiled0: { name: "Shiled", description: "A shiled.", attack: 1, defense: 5, value: 30, type: "shield" , health: 0},
    shield1: { name: "Shield", description: "A sturdy shield.", attack: 1, defense: 10, value: 20, type: "shield" , health: 0},
    chest0: { name: "Chest", description: "A chest.", attack: 0, defense: 0, value: 0, type: "chest" , health: 10},
    elixir0: { name: "Elixir", description: "A magical elixir.", attack: 0, defense: 0, value: 20, type: "potion" , health: 5},
    elixir1: { name: "Elixir", description: "A magical elixir.", attack: 1, defense: 1, value: 20, type: "potion" , health: 10},
    elixir2: { name: "Elixir", description: "A magical elixir.", attack: 2, defense: 2, value: 50, type: "potion" , health: 15},
    elixir3: { name: "Elixir", description: "A magical elixir.", attack: 3, defense: 3, value: 80, type: "potion" , health: 100},
    potion0: { name: "Potion", description: "A magical potion.", attack: 0, defense: 0, value: 10, type: "potion" , health: 1},
    potion1: { name: "Potion", description: "A magical potion.", attack: 1, defense: 1, value: 5, type: "potion" , health: 5},
    potion2: { name: "Potion", description: "A magical potion.", attack: 1, defense: 1, value: 8, type: "potion" , health: 8},
    potion3: { name: "Potion", description: "A magical potion.", attack: 1, defense: 1,value: 10, type: "potion", health: 10},
    axe: {name: "Axe", description: "A sharp axe for cutting and chopping.", attack: 8, defense: 2, value: 50, type: "weapon" , health: 10},
};

