export default  {
  axe: {
    name: "Axe",
    description: "A sharp axe for cutting and chopping.",
    attack: 8,
    defense: 2,
    value: 50,
    type: "weapon"
  },
  big_rat: {
    name: "Big Rat",
    description: "A large rat with sharp teeth.",
    attack: 3,
    defense: 1,
    value: 10,
    type: "enemy"
  },
  dagger: { name: "Dagger", description: "A small and agile dagger.", attack: 5, defense: 1, value: 10, type: "weapon"},
  elixir3: {  name: "Elixir",  description: "A magical elixir.",  attack: 0,  defense: 0,  value: 10,  type: "potion"},
  monster: {  name: "Monster",  description: "A large and scary monster.",  attack: 10,  defense: 5,  value: 100,  type: "enemy"},
  potion3: {  name: "Potion",  description: "A magical potion.",  attack: 0,  defense: 0,  value: 100,  type: "potion"},
  shield1: {  name: "Shield",  description: "A sturdy shield.",  attack: 0,  defense: 5,  value: 20,  type: "shield"},
  staff3: {  name: "Staff",  description: "A magical staff.",  attack: 5,  defense: 0,  value: 30,  type: "weapon"},
  barbarian: {  name: "Barbarian",  description: "A barbarian.",  attack: 10,  defense: 5,  value: 100,  type: "enemy"},
  chaos_warrior: {  name: "Chaos Warrior",  description: "A chaos warrior.",  attack: 10,  defense: 5,  value: 100,  type: "enemy"},
  dwarf: {  name: "Dwarf",  description: "A dwarf.",  attack: 10,  defense: 5,  value: 100,  type: "enemy"},
  evil_chest: {  name: "Evil Chest",  description: "An evil chest.",  attack: 10,  defense: 5,  value: 100,  type: "enemy"},
  paladin: {  name: "Paladin",  description: "A paladin.",  attack: 10,  defense: 5,  value: 100,  type: "enemy"},
  priest: {  name: "Priest",  description: "A priest.",  attack: 10,  defense: 5,  value: 100,  type: "enemy"},
  shiled0: {  name: "Shiled",  description: "A shiled.",  attack: 0,  defense: 5,  value: 30,  type: "shield"},
  sword0: {  name: "Sword",  description: "A sword.",  attack: 10,  defense: 0,  value: 30,  type: "weapon"},
  barbarian2: {  name: "Barbarian",  description: "A barbarian.",  attack: 10,  defense: 5,  value: 100,  type: "enemy"},
  chest0: {  name: "Chest",  description: "A chest.",  attack: 0,  defense: 0,  value: 100,  type: "chest"},
  elixir0: {  name: "Elixir",  description: "A magical elixir.",  attack: 0,  defense: 0,  value: 20,  type: "potion"},
  ghost: {  name: "Ghost",  description: "A ghost.",  attack: 10,  defense: 5,  value: 100,  type: "enemy"},
  potion0: {  name: "Potion",  description: "A magical potion.",  attack: 0,  defense: 0,  value: 10,  type: "potion"},
  princess: {  name: "Princess",  description: "A princess.",  attack: 10,  defense: 5,  value: 100,  type: "enemy"},
  spider: {  name: "Spider",  description: "A spider.",  attack: 10,  defense: 5,  value: 100,  type: "enemy"},
  sword1: {  name: "Sword",  description: "A sword.",  attack: 10,  defense: 0,  value: 50,  type: "weapon"},
  warlock: {  name: "Warlock",  description: "A warlock.",  attack: 10,  defense: 5,  value: 100,  type: "enemy"},
  bat: {  name: "Bat",  description: "A bat.",  attack: 10,  defense: 5,  value: 100,  type: "enemy"},
  chest2: {  name: "Chest",  description: "A chest.",  attack: 0,  defense: 0,  value: 100,  type: "chest"},
  elixir1: {  name: "Elixir",  description: "A magical elixir.",  attack: 0,  defense: 0,  value: 20,  type: "potion"},
  hammer: {  name: "Hammer",  description: "A hammer.",  attack: 10,  defense: 0,  value: 60,  type: "weapon"},
  potion1: {  name: "Potion",  description: "A magical potion.",  attack: 0,  defense: 0,  value: 15,  type: "potion"},
  rat: {  name: "Rat",  description: "A rat.",  attack: 10,  defense: 5,  value: 100,  type: "enemy"},
  staff1: {  name: "Staff",  description: "A magical staff.",  attack: 5,  defense: 0,  value: 35,  type: "weapon"},
  sword2: {  name: "Sword",  description: "A sword.",  attack: 10,  defense: 0,  value: 70,  type: "weapon"},
  wizard: {  name: "Wizard",  description: "A wizard.",  attack: 10,  defense: 5,  value: 100,  type: "enemy"},
  battle_axe: {  name: "Battle Axe",  description: "A battle axe.",  attack: 10,  defense: 0,  value: 100,  type: "weapon"},
  chest3: {  name: "Chest",  description: "A chest.",  attack: 0,  defense: 0,  value: 100,  type: "chest"},
  elixir2: {  name: "Elixir",  description: "A magical elixir.",  attack: 0,  defense: 0,  value: 50,  type: "potion"},
  knight: {  name: "Knight",  description: "A knight.",  attack: 10,  defense: 5,  value: 100,  type: "enemy"},
  potion2: {  name: "Potion",  description: "A magical potion.",  attack: 0,  defense: 0,  value: 20,  type: "potion"},
  scorpion: {  name: "Scorpion",  description: "A scorpion.",  attack: 10,  defense: 5,  value: 100,  type: "enemy"},
  staff2: {  name: "Staff",  description: "A magical staff.",  attack: 5,  defense: 0,  value: 100,  type: "weapon"},
  sword3: {  name: "Sword",  description: "A sword.",  attack: 10,  defense: 0,  value: 80,  type: "weapon"},
  wrath: {  name: "Wrath",  description: "A wrath.",  attack: 10,  defense: 5,  value: 100,  type: "enemy"}
};

