export default {
    text: {title: "DEFAULT", size: 40, items: [{ text: "Pello"}] },
    text1: {title: "Presenta", size: 40, items: [{ text: "Pello"}] },
    text2: {title: "Teclea", size: 40, items: [{ text: "Josu"}] },
    text3: {title: "Aprende", size: 40, items: [{ text: "Quien quiera"}] },
    text4: {title: "!Teclea con nostros!", size: 40, items: [{}] },
    text5: {title: "Prepara", size: 40, items: [{text: "Las herramientas"}] },
    text6: {title: "Where? itch.io", size: 40, items: [{text: "Creators"}, {text: "Games"}, {text: "Assets"}, {text: "JAMS!"}] },
    text7: {title: "Game: ARKAPONG", size: 40, items: [{text: "Formal"}, {text: "As homework"}, {text: "Sound effects: sfxr.me"}] },
    text8: {title: "Game: Flatulent World", size: 40, items: [{text: "Bubble bobble, Snow Bros,..."}, {text: "Animations: piskel"}] },
    text9: {title: "JAMS", size: 40, items: [{text: "Indie game contest"}, {text: "Game from Scratch"}, {text: "Short time"}, {text: "Topic based"}] },
    text10: {title: "Game: Truck Track", size: 40, items: [{text: "Massive Jam"}, {text: "Topic: 'Too Long'"}] },
    text11: {title: "Mini JaM", size: 40, items: [{text: "Every two weeks"}, {text: "Weekend"}, {text: "Topic & Limit"}, {text: "No ceremony..."} ] },
    text12: {title: "Game: Spooky", size: 40, items: [{text: "Topic: pumpkin, Limit: Myth"}, {text: "Tilemap: tiled"}, {text: "Tweens and effects"}, {text: "Feedback + Reviews"}] },
    text13: {title: "Game: Weezard", size: 40, items: [{text: "Topic: illusion"}, {text: "Limit: single character"}, {text: "Big map, camera effects"}] },
    text14: {title: "What is a game?", size: 40, items: [{text: "Code?"}, {text: "Creation"}, {text: "Story & World"}, {text: "Product"}] },
    text15: {title: "What I learned?", size: 40, items: [{text: "Fun"}, {text: "Learn code, tricks"}] },
    text16: {title: "What I really learned?", size: 40, items: [{text: "Nobody cares about your code"}, {text: "Many skills"}, {text: "Arbitrary"}] },
    text17: {title: "Goal?", size: 40, items: [{text: "Fun + Creation + Learning"}, {text: "Improvement"}, {text: "New stuff"}] },
    text18: {title: "Long Term Goal", size: 40, items: [{text: "The Holy Grail"}] },
    text19: {title: "Game Over", size: 40, items: [] },
}